// Глоссарий: статистические термины + бизнес-метрики из иерархий.
// aliases — синонимы для поиска (рус/англ/аббревиатуры), в выдаче не показываются.
// lesson — slug урока (/stats/<lesson>), где термин разобран интерактивно.
export const glossary = [
  {
    group: 'Статистика',
    terms: [
      { term: 'Среднее', def: 'Сумма значений, делённая на их количество. Чувствительно к выбросам.', aliases: ['mean', 'среднее арифметическое'], lesson: 'center-measures' },
      { term: 'Медиана', def: 'Значение ровно посередине упорядоченного ряда. Устойчива к выбросам.', aliases: ['median'], lesson: 'center-measures' },
      { term: 'Мода', def: 'Самое частое значение. Полезна для категорий.', aliases: ['mode'], lesson: 'center-measures' },
      { term: 'Дисперсия', def: 'Среднее квадратов отклонений от среднего; разброс данных в «квадратных» единицах.', aliases: ['variance', 'разброс'], lesson: 'spread' },
      { term: 'Стандартное отклонение (σ)', def: 'Корень из дисперсии — типичное отклонение от среднего в тех же единицах, что данные.', aliases: ['std', 'sd', 'сигма', 'standard deviation'], lesson: 'spread' },
      { term: 'Перцентиль / квартиль', def: 'Значение, ниже которого лежит заданная доля данных (Q1 — 25%, медиана — 50%, Q3 — 75%).', aliases: ['percentile', 'quantile', 'квантиль', 'p95', 'p99'], lesson: 'percentiles' },
      { term: 'Нормальное распределение', def: 'Симметричный «колокол», заданный μ и σ. Правило 68-95-99.7.', aliases: ['гаусс', 'gaussian', 'колокол'], lesson: 'normal-distribution' },
      { term: 'Скошенность (skew)', def: 'Несимметричность распределения; длинный хвост с одной стороны.', aliases: ['асимметрия', 'skewness', 'длинный хвост'], lesson: 'skew-tail' },
      { term: 'Вероятность', def: 'Доля случаев, в которых событие происходит на длинной серии (от 0 до 1).', aliases: ['probability'], lesson: 'probability-basics' },
      { term: 'Закон больших чисел', def: 'С ростом числа испытаний наблюдаемая доля стремится к истинной вероятности.', aliases: ['LLN', 'ЗБЧ'], lesson: 'probability-lln' },
      { term: 'Условная вероятность', def: 'Вероятность события при условии, что известно другое. P(A|B) ≠ P(B|A).', aliases: ['conditional probability'], lesson: 'conditional-bayes' },
      { term: 'Теорема Байеса', def: 'Правило обновления вероятности с учётом новых данных и базовой ставки.', aliases: ['bayes', 'байес'], lesson: 'conditional-bayes' },
      { term: 'ЦПТ', def: 'Центральная предельная теорема: распределение средних выборок стремится к нормальному.', aliases: ['CLT', 'центральная предельная теорема'], lesson: 'clt' },
      { term: 'Стандартная ошибка', def: 'Типичный случайный разброс оценки (напр. среднего); убывает как 1/√n.', aliases: ['SE', 'standard error'], lesson: 'sampling-statistic' },
      { term: 'Доверительный интервал', def: 'Диапазон, в котором при повторении опыта заданная доля интервалов (95%) накрывает истину.', aliases: ['CI', 'confidence interval'], lesson: 'confidence-intervals' },
      { term: 'Бутстреп', def: 'Оценка неопределённости через пересоставление выборки из самой себя с возвратом.', aliases: ['bootstrap'], lesson: 'bootstrap' },
      { term: 'Нулевая гипотеза (H0)', def: 'Предположение «эффекта нет»; его пытаются опровергнуть.', aliases: ['null hypothesis'], lesson: 'hypothesis-intro' },
      { term: 'p-value', def: 'Вероятность получить такой результат, если эффекта нет. Маленький p — случайностью объяснить трудно.', aliases: ['п-значение', 'значимость', 'significance'], lesson: 'hypothesis-test' },
      { term: 'Ошибка 1 рода (α)', def: 'Ложное срабатывание: объявить эффект, которого нет.', aliases: ['alpha', 'false positive', 'ложное срабатывание'], lesson: 'hypothesis-test' },
      { term: 'Ошибка 2 рода (β)', def: 'Пропуск: проглядеть реальный эффект. Мощность = 1−β.', aliases: ['beta', 'false negative', 'пропуск эффекта'], lesson: 'hypothesis-test' },
      { term: 'Мощность', def: 'Вероятность обнаружить эффект, если он есть.', aliases: ['power', 'чувствительность теста'], lesson: 'power-sample-size' },
      { term: 't-тест', def: 'Проверка, значимо ли различаются средние двух групп.', aliases: ['t-test', 'стьюдент'], lesson: 'stat-criteria' },
      { term: 'Множественные сравнения', def: 'Проверка многих гипотез сразу; ложные срабатывания накапливаются (поправка Бонферрони).', aliases: ['bonferroni', 'бонферрони', 'FDR'], lesson: 'multiple-comparisons' },
      { term: 'Корреляция (r)', def: 'Число от −1 до +1: сила и направление линейной связи. Не равна причинности.', aliases: ['correlation', 'пирсон', 'спирмен'], lesson: 'correlation-types' },
      { term: 'Регрессия / МНК', def: 'Прямая, минимизирующая сумму квадратов ошибок; предсказывает одну величину по другой.', aliases: ['regression', 'OLS', 'линейная регрессия'], lesson: 'regression' },
      { term: 'Парадокс Симпсона', def: 'Связь в целом меняет знак при разбиении данных на группы.', aliases: ['simpson'], lesson: 'simpson-paradox' },
      { term: 'Переобучение', def: 'Модель заучила шум обучающих данных и плохо работает на новых.', aliases: ['overfitting', 'train test'], lesson: 'overfitting' },
      { term: 'Precision / Recall', def: 'Точность — какая доля помеченных верна; полнота — какую долю нужного класса поймали.', aliases: ['точность', 'полнота'], lesson: 'confusion-matrix' },
      { term: 'ROC / AUC', def: 'Кривая качества классификатора при всех порогах; AUC — площадь под ней (1 — идеал, 0.5 — случай).', aliases: ['рок-кривая'], lesson: 'roc' },
      { term: 'Ошибка выжившего', def: 'Вывод по «дожившим» до данных при игнорировании выпавших из них.', aliases: ['survivorship bias'], lesson: 'survivorship-bias' },
      { term: 'Закон Гудхарта', def: 'Когда мера становится целью, её начинают накручивать, и она перестаёт быть хорошей мерой.', aliases: ['goodhart'], lesson: 'goodhart' },
    ],
  },
  {
    group: 'Бизнес-метрики',
    terms: [
      { term: 'North Star Metric', def: 'Главная метрика, лучше всего отражающая ключевую ценность продукта.', aliases: ['NSM', 'северная звезда'] },
      { term: 'DAU / MAU', def: 'Daily / Monthly Active Users — активные пользователи за день / месяц.', aliases: ['активная аудитория', 'stickiness'] },
      { term: 'Retention', def: 'Удержание: доля пользователей, вернувшихся через 1/7/30 дней.', aliases: ['удержание', 'ретеншен'] },
      { term: 'Churn', def: 'Отток: доля пользователей или подписчиков, ушедших за период.', aliases: ['отток'] },
      { term: 'ARPU / ARPPU', def: 'Средний доход на пользователя / на платящего пользователя.', aliases: ['средний доход на пользователя'] },
      { term: 'LTV', def: 'Пожизненная ценность клиента — суммарный доход с него за всё время.', aliases: ['lifetime value', 'пожизненная ценность'] },
      { term: 'CAC', def: 'Стоимость привлечения клиента. Здоровье: LTV ≥ 3× CAC.', aliases: ['стоимость привлечения'] },
      { term: 'GMV', def: 'Gross Merchandise Value — общий оборот товаров на платформе.', aliases: ['оборот'] },
      { term: 'Take Rate', def: 'Эффективная комиссия платформы — доля GMV, остающаяся ей.', aliases: ['комиссия платформы'] },
      { term: 'Conversion Rate (CR)', def: 'Доля пользователей, совершивших целевое действие.', aliases: ['конверсия'] },
      { term: 'AOV', def: 'Average Order Value — средний чек заказа.', aliases: ['средний чек'] },
      { term: 'NRR', def: 'Net Revenue Retention — рост выручки от уже имеющихся клиентов (>100% — растут без новых).', aliases: ['net revenue retention'] },
      { term: 'MRR', def: 'Monthly Recurring Revenue — регулярная месячная выручка подписки.', aliases: ['подписочная выручка'] },
      { term: 'Fulfillment / Match Rate', def: 'Доля запросов, завершившихся успешной сделкой/поездкой — качество матчинга.', aliases: ['матчинг'] },
      { term: 'Same-store sales', def: 'Продажи на существующих точках (без учёта новых открытий) — честный рост сети.', aliases: ['LFL', 'like-for-like'] },
      { term: 'Контр-метрики (Guardrails)', def: 'Ограничители качества рядом с целевой метрикой; ловят накрутку (закон Гудхарта).', aliases: ['гардрейлы', 'guardrail'], lesson: 'goodhart' },
      { term: 'ACV', def: 'Annual Contract Value — среднегодовая стоимость контракта одного клиента в B2B/SaaS.', aliases: ['annual contract value'] },
      { term: 'ARR', def: 'Annual Recurring Revenue — годовая регулярная выручка подписочного бизнеса; ARR = MRR × 12.', aliases: ['annual recurring revenue'] },
      { term: 'KYC', def: 'Know Your Customer — проверка личности клиента при открытии счёта; обязательна в банках и финтехе.', aliases: ['know your customer'] },
      { term: 'Interchange', def: 'Комиссия, которую платёжная система удерживает с каждой карточной транзакции; основной источник дохода необанков.', aliases: [] },
      { term: 'TPV', def: 'Total Payment Volume — общий объём платежей, прошедших через платформу; аналог GMV для финтеха.', aliases: ['total payment volume'] },
      { term: 'SKU', def: 'Stock Keeping Unit — уникальная позиция товара в каталоге; ширину ассортимента считают числом SKU.', aliases: ['stock keeping unit'] },
      { term: 'FBO', def: 'Fulfillment by Operator — хранение и отгрузка товара со склада самой платформы, а не продавца.', aliases: ['fulfillment by operator'] },
      { term: 'GBV', def: 'Gross Booking Value — общая стоимость забронированных услуг на платформе; аналог GMV для трэвел-сервисов.', aliases: ['gross booking value'] },
      { term: 'TAC', def: 'Traffic Acquisition Cost — плата поисковика партнёрам за то, что он установлен поиском по умолчанию.', aliases: ['traffic acquisition cost'] },
      { term: 'ROAS / ДРР', def: 'Return on Ad Spend — выручка на рубль рекламных расходов; обратная величина — ДРР, доля рекламных расходов в выручке.', aliases: ['return on ad spend', 'дрр'] },
      { term: 'NPS', def: 'Net Promoter Score — индекс лояльности: доля рекомендующих продукт минус доля критикующих.', aliases: ['net promoter score'] },
      { term: 'CPI', def: 'Cost Per Install — стоимость одной установки приложения; ключевая метрика привлечения в играх.', aliases: ['cost per install'] },
      { term: 'UA', def: 'User Acquisition — привлечение пользователей: команда, бюджет и каналы притока новых игроков или клиентов.', aliases: ['user acquisition'] },
      { term: 'F2P', def: 'Free-to-Play — модель, где продукт бесплатен для всех, а выручку приносит меньшинство платящих.', aliases: ['free-to-play'] },
      { term: 'D1 / D7 / D30', def: 'Retention на 1-й / 7-й / 30-й день: доля пользователей, вернувшихся ровно через столько дней после установки.', aliases: ['retention day', 'd1', 'd7', 'd30'] },
      { term: 'ETA', def: 'Estimated Time of Arrival — расчётное время прибытия курьера, водителя или заказа.', aliases: ['estimated time of arrival'] },
      { term: 'LMS', def: 'Learning Management System — платформа для проведения и учёта онлайн-курсов.', aliases: ['learning management system'] },
      { term: 'RPM', def: 'Revenue Per Mille — доход на тысячу просмотров; метрика монетизации авторов на видеоплатформах.', aliases: ['revenue per mille'] },
      { term: 'CPC', def: 'Cost Per Click — цена одного клика по рекламному объявлению в аукционе.', aliases: ['cost per click'] },
      { term: 'SEM', def: 'Search Engine Marketing — платное продвижение в поисковой выдаче, в отличие от бесплатного SEO.', aliases: ['search engine marketing'] },
      { term: 'Look-to-Book', def: 'Доля поисковых сессий, завершившихся бронированием; ключевая конверсия в трэвел-сервисах.', aliases: ['look to book'] },
      { term: 'Contribution margin', def: 'Маржинальная прибыль — выручка минус переменные затраты на единицу (заказ, поездку).', aliases: ['маржинальная прибыль'] },
      { term: 'Bookings', def: 'Сумма всех платежей игроков за период до вычета комиссии магазинов приложений; выручка F2P-игр.', aliases: [] },
      { term: 'Trial → Paid', def: 'Конверсия из пробного периода в платящего подписчика.', aliases: ['trial to paid'] },
      { term: 'CTR', def: 'Click-Through Rate — доля кликнувших среди увидевших объявление, превью или ссылку.', aliases: ['click-through rate', 'кликабельность'] },
      { term: 'SEO', def: 'Search Engine Optimization — бесплатное продвижение в поисковой выдаче за счёт релевантности сайта.', aliases: ['search engine optimization'] },
      { term: 'B2B / B2C', def: 'Business-to-business / business-to-consumer — продажа компаниям или напрямую конечным потребителям.', aliases: ['b2b', 'b2c'] },
    ],
  },
]
