// English glossary: same structure and lesson slugs as the Russian one.
export const glossaryEn = [
  {
    group: 'Statistics',
    terms: [
      { term: 'Mean', def: 'Sum of all values divided by their count. Sensitive to outliers.', aliases: ['average', 'arithmetic mean'], lesson: 'center-measures' },
      { term: 'Median', def: 'The value exactly in the middle of the sorted list. Robust to outliers.', aliases: ['middle value'], lesson: 'center-measures' },
      { term: 'Mode', def: 'The most frequent value. Useful for categories.', aliases: [], lesson: 'center-measures' },
      { term: 'Variance', def: 'Average of squared deviations from the mean; spread in "squared" units.', aliases: ['dispersion'], lesson: 'spread' },
      { term: 'Standard deviation (σ)', def: 'Square root of variance: the typical deviation from the mean, in the same units as the data.', aliases: ['std', 'sd', 'sigma'], lesson: 'spread' },
      { term: 'Percentile / quartile', def: 'The value below which a given share of the data lies (Q1 is 25%, the median 50%, Q3 75%).', aliases: ['quantile', 'p95', 'p99'], lesson: 'percentiles' },
      { term: 'Normal distribution', def: 'The symmetric "bell" defined by μ and σ. The 68-95-99.7 rule.', aliases: ['gaussian', 'bell curve'], lesson: 'normal-distribution' },
      { term: 'Skewness', def: 'Asymmetry of a distribution; a long tail on one side.', aliases: ['skew', 'long tail'], lesson: 'skew-tail' },
      { term: 'Probability', def: 'The share of cases in which an event happens over a long run (from 0 to 1).', aliases: [], lesson: 'probability-basics' },
      { term: 'Law of large numbers', def: 'As trials accumulate, the observed share converges to the true probability.', aliases: ['LLN'], lesson: 'probability-lln' },
      { term: 'Conditional probability', def: 'Probability of an event given that another is known. P(A|B) ≠ P(B|A).', aliases: [], lesson: 'conditional-bayes' },
      { term: 'Bayes’ theorem', def: 'The rule for updating a probability with new data and the base rate.', aliases: ['bayes'], lesson: 'conditional-bayes' },
      { term: 'CLT', def: 'Central limit theorem: the distribution of sample means tends to normal.', aliases: ['central limit theorem'], lesson: 'clt' },
      { term: 'Standard error', def: 'Typical random spread of an estimate (e.g. of a mean); shrinks as 1/√n.', aliases: ['SE'], lesson: 'sampling-statistic' },
      { term: 'Confidence interval', def: 'A range built so that, over repeated experiments, a set share of intervals (95%) covers the truth.', aliases: ['CI'], lesson: 'confidence-intervals' },
      { term: 'Bootstrap', def: 'Estimating uncertainty by resampling the sample from itself with replacement.', aliases: [], lesson: 'bootstrap' },
      { term: 'Null hypothesis (H0)', def: 'The "no effect" assumption; the one you try to reject.', aliases: ['null'], lesson: 'hypothesis-intro' },
      { term: 'p-value', def: 'Probability of a result at least this extreme if there is no effect. Small p means chance is a poor explanation.', aliases: ['significance'], lesson: 'hypothesis-test' },
      { term: 'Type I error (α)', def: 'False alarm: declaring an effect that does not exist.', aliases: ['alpha', 'false positive'], lesson: 'hypothesis-test' },
      { term: 'Type II error (β)', def: 'A miss: overlooking a real effect. Power = 1−β.', aliases: ['beta', 'false negative'], lesson: 'hypothesis-test' },
      { term: 'Power', def: 'The chance of detecting an effect when it truly exists.', aliases: ['sensitivity'], lesson: 'power-sample-size' },
      { term: 't-test', def: 'A test of whether the means of two groups differ significantly.', aliases: ['student'], lesson: 'stat-criteria' },
      { term: 'Multiple comparisons', def: 'Testing many hypotheses at once; false alarms pile up (Bonferroni correction).', aliases: ['bonferroni', 'FDR'], lesson: 'multiple-comparisons' },
      { term: 'Correlation (r)', def: 'A number from −1 to +1: strength and direction of a linear relationship. Not causation.', aliases: ['pearson', 'spearman'], lesson: 'correlation-types' },
      { term: 'Regression / OLS', def: 'The line minimizing squared errors; predicts one quantity from another.', aliases: ['linear regression', 'least squares'], lesson: 'regression' },
      { term: 'Simpson’s paradox', def: 'An overall relationship flips sign when the data is split into groups.', aliases: ['simpson'], lesson: 'simpson-paradox' },
      { term: 'Overfitting', def: 'The model memorized the noise of the training data and fails on new data.', aliases: ['train test'], lesson: 'overfitting' },
      { term: 'Precision / Recall', def: 'Precision: what share of flagged items is correct; recall: what share of the target class you caught.', aliases: [], lesson: 'confusion-matrix' },
      { term: 'ROC / AUC', def: 'Classifier quality curve across all thresholds; AUC is the area under it (1 is ideal, 0.5 is chance).', aliases: [], lesson: 'roc' },
      { term: 'Survivorship bias', def: 'Drawing conclusions from what "survived" into the data while ignoring what dropped out.', aliases: [], lesson: 'survivorship-bias' },
      { term: 'Goodhart’s law', def: 'When a measure becomes a target, it gets gamed and stops being a good measure.', aliases: ['goodhart'], lesson: 'goodhart' },
    ],
  },
  {
    group: 'Business metrics',
    terms: [
      { term: 'North Star Metric', def: 'The single metric that best reflects the core value of the product.', aliases: ['NSM'] },
      { term: 'DAU / MAU', def: 'Daily / Monthly Active Users; their ratio is "stickiness".', aliases: ['active users', 'stickiness'] },
      { term: 'Retention', def: 'The share of users who come back after 1/7/30 days.', aliases: [] },
      { term: 'Churn', def: 'The share of users or subscribers who left during a period.', aliases: [] },
      { term: 'ARPU / ARPPU', def: 'Average revenue per user / per paying user.', aliases: [] },
      { term: 'LTV', def: 'Lifetime value: total revenue from a customer over their whole life.', aliases: ['lifetime value'] },
      { term: 'CAC', def: 'Customer acquisition cost. Healthy when LTV ≥ 3× CAC.', aliases: ['acquisition cost'] },
      { term: 'GMV', def: 'Gross Merchandise Value: total value of goods sold through the platform.', aliases: ['turnover'] },
      { term: 'Take Rate', def: 'The platform’s effective commission: the share of GMV it keeps.', aliases: ['commission'] },
      { term: 'Conversion Rate (CR)', def: 'The share of users who completed the target action.', aliases: ['conversion'] },
      { term: 'AOV', def: 'Average Order Value.', aliases: ['average check'] },
      { term: 'NRR', def: 'Net Revenue Retention: revenue growth from existing customers (>100% means growth without new ones).', aliases: [] },
      { term: 'MRR', def: 'Monthly Recurring Revenue of a subscription business.', aliases: [] },
      { term: 'Fulfillment / Match Rate', def: 'The share of requests that ended in a successful deal or ride; matching quality.', aliases: ['matching'] },
      { term: 'Same-store sales', def: 'Sales of existing locations (excluding new openings): honest chain growth.', aliases: ['LFL', 'like-for-like'] },
      { term: 'Guardrail metrics', def: 'Quality limits watched alongside the target metric; they catch gaming (Goodhart’s law).', aliases: ['counter-metrics'], lesson: 'goodhart' },
    ],
  },
]
